### ISSUE TITLE
quotes and asset and archive digest endpoints

### ISSUE THREAD

**Issue by nsheff** [databio/refgenieserver#67]
is there a reason the digest endpoints return the digests with quotes?

http://staging.refgenomes.databio.org/v2/asset/hg19/fasta/default/archive_digest?tag=default

```
"06e47db59dad7054c4b45df7abbaef20"
```

**Comment by nsheff** [comment]
also: http://staging.refgenomes.databio.org/v2/asset/hg19/fasta/default/asset_digest?tag=default

"7ce3b03e30d6ef76af8c3ad09a141dfc"

**Comment by stolarczyk** [comment]
we `return` a python `str` from the endpoint and in the FastAPI docs they say that some behind the scenes preprocessing is performed upon `return`:
https://fastapi.tiangolo.com/tutorial/response-directly/ so that's probably a result of that.
Also, any client applications that will query the server to get the digest should handle this JSON properly, as they expect a string anyway, right?

**Comment by nsheff** [comment]
I see. I guess I don't really feel the need to return it as a JSON if it's an atomic output like that...what if you're just hitting it from somewhere like a command line or something? you'd have to pipe to `jq` to parse it, even for atomic endpoints... what do you think?

**Comment by nsheff** [comment]
I think we need to switch this.

It's inconvenient to get a string with quotes for something like this: http://rg.databio.org/assets/file_path/2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta/fasta?remoteClass=http

now in particular when we're returning paths. the quotes offer no advantage as far as I can see.
